# Build the Twitter Pinboard Cleanup Job
# https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  env:
    TWITTER_TWI_CLIENT_KEY: ${{ secrets.TWITTER_TWI_CLIENT_KEY }}
    TWITTER_TWI_CLIENT_KEY_SECRET: ${{ secrets.TWITTER_TWI_CLIENT_KEY_SECRET }}
    PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}
    CF_USER: ${{ secrets.CF_USER }}
    CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
    CF_SPACE: ${{ secrets.CF_SPACE }}
    CF_API: ${{ secrets.CF_API }}
    CF_ORG: ${{ secrets.CF_ORG  }}

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          #          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      #        env:
      #          TWITTER_TWI_CLIENT_KEY: ${{ secrets.TWITTER_TWI_CLIENT_KEY }}
      #          TWITTER_TWI_CLIENT_KEY_SECRET: ${{ secrets.TWITTER_TWI_CLIENT_KEY_SECRET }}
      #          PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}

      - name: Deploy to Cloud Foundry
        #        env:
        #          TWITTER_TWI_CLIENT_KEY: ${{ secrets.TWITTER_TWI_CLIENT_KEY }}
        #          TWITTER_TWI_CLIENT_KEY_SECRET: ${{ secrets.TWITTER_TWI_CLIENT_KEY_SECRET }}
        #          PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}
        #          CF_USER: ${{ secrets.CF_USER }}
        #          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        #          CF_SPACE: ${{ secrets.CF_SPACE }}
        #          CF_API: ${{ secrets.CF_API }}
        #          CF_ORG: ${{ secrets.CF_ORG  }}
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          ./deploy/cf.sh
          ./deploy/deploy.sh