# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Cached resolved dependencies like Maven artifacts
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-maven-dependencies
      with:
        path: ~/.m2 # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        pwd 
        cd $GITHUB_WORKSPACE 
        pwd
        mvn -e verify deploy 
        ./deploy/cf.sh
        ./deploy/deploy.sh
        

